version: 2.1

orbs:
  snyk: snyk/snyk@0.0.8

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gem-cache-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache
      - run:
          name: Install ruby dependencies
          command: |
            gem update --system
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - v2-npm-cache-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Install node dependencies
          command: npm install
      - save_cache:
          key: v2-npm-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - node_modules
      - run:
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run:
          name: Build site files
          command: npm run build
      - run:
          name: Install scss_lint
          command: gem install scss_lint
      - snyk/scan:
          organization: uswds
      - run:
          name: Run test
          command: npm run test:ci

workflows:
  version: 2.1
  circle-uswds-site:
    jobs:
      - build
